# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: rundeck-bridge
# Spec:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'rundeck-bridge::default' do
  context 'When all attributes are default, on centos 7.2.1511' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new(
        platform: 'centos',
        version:  '7.2.1511'
      )
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end

    it 'configure chef-client' do
      expect(chef_run).to render_file('/etc/chef/client.rb')
    end

    it 'bug workaround' do
      expect(chef_run).to render_file('/etc/chef/client.d/chef-rundeck.rb')
        .with_content('log_level :info')
    end

    it 'install gem' do
      expect(chef_run).to install_chef_gem('chef-rundeck')
    end
  end
end
